# 1st stage
FROM node:18 as build

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

# 2nd stage
FROM node:18

ENV NODE_ENV production

WORKDIR /app

COPY --from=build app/package*.json .

RUN npm install --only=production

COPY --from=build /app/dist ./dist
COPY --from=build /app/public ./public

ENV PORT 5000

EXPOSE $PORT

CMD ["npm", "start"]